name: Check

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Danger
        uses: danger/kotlin@1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  no_accessors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Don't allow any accessor imports
        run: if grep --include=\*.{kt,kts} -rne 'import gradle\.kotlin\.dsl\.accessors\._' .; then false; else true; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Ensure project builds
        run: ./gradlew build

  detektWithTypeResolution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Run detekt with type resolution
        run: ./gradlew :conventions-base:detektMain :conventions-detekt:detektMain :conventions-kotlin:detektMain

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run ktlint
        run: ./format --no-format


env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
