name: Check

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Danger
        uses: docker://ghcr.io/danger/danger-kotlin:1.1.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  no_accessors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Don't allow any accessor imports
        run: if grep --include=\*.{kt,kts} -rne 'import gradle\.kotlin\.dsl\.accessors\._' .; then false; else true; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          gradle-version: wrapper

      - name: Ensure project builds
        run: ./gradlew build

  detektWithTypeResolution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          gradle-version: wrapper

      - name: Ensure project builds
        run: ./gradlew detektMain


env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
